feat: add all recommended and must supported schema formats
asyncapi/spec-json-schemas pull request #365
Opened 2023-03-16 15:39 UTC by jonaslagoni

**Description**
This PR adds all the MUST and RECOMMENDED supported schema formats. This is to enable auto-completion more than anything because the underlying type is `string`, it's only to help know which known values are there.

2023-03-16 16:12 UTC, GreenRover commented
If tooling will support proto but it is not listed here it is not a problem?

2023-03-16 16:15 UTC, jonaslagoni commented
These are just all known schema formats listed in https://www.asyncapi.com/docs/reference/specification/v2.6.0#messageObjectSchemaFormatTable

We cannot add values we haven't agreed upon, you can of course still use custom ones.

Adding new keys for other schema formats is part of the spec discussion.

2023-03-30 14:50 UTC, derberg reviewed
looks like manual stuff that will have to be updated with each release

not a problem, just mentioning because this requires updates in readme, and probably script that generates new version definitions?

2023-04-25 14:25 UTC, jonaslagoni commented on definitions/3.0.0/messageObject.json
> +            "application/vnd.aai.asyncapi+yaml;version=2.6.0",
There are two reasons why I am suggesting to have them:
- Code generation, i.e. that these types are generated and easier to use.
- Auto-completion, i.e. it's easier to remember the actual values and for the user.

From a validation point of view, they don't matter.

2023-04-25 14:35 UTC, derberg commented on definitions/3.0.0/messageObject.json
> +            "application/vnd.aai.asyncapi+yaml;version=2.6.0",
but why below is not enough event for code gen and autocompletion, sorry but I don't get 😅 
```
"application/vnd.aai.asyncapi;version=3.0.0",
"application/vnd.aai.asyncapi+json;version=3.0.0",
"application/vnd.aai.asyncapi+yaml;version=3.0.0",
```

2023-04-25 15:00 UTC, jonaslagoni commented on definitions/3.0.0/messageObject.json
> +            "application/vnd.aai.asyncapi+yaml;version=2.6.0",
He he, probably not 😄

I can remove previous versions 👍

2023-04-25 15:01 UTC, jonaslagoni commented
> not a problem, just mentioning because this requires updates in readme, and probably script that generates new version definitions?

I'll see if I can include it in the script, that would be easiest yea.

2023-06-29 14:30 UTC, jonaslagoni commented
Alright, I made a few changes.

1. Adapted the create new version script:
  - Before, we could accidentally replace versions that were unintended, i.e. it would happen in the next version (3.1.0) because it would replace the `application/vnd.oai.openapi;version=3.0.0` to `application/vnd.oai.openapi;version=3.1.0`. 
  - If the new version is a major version change (i.e. first number is not equal to the latest), replace all AsyncAPI schema format entries with the new.
  - If the new version is minor or fix, add a new entry of AsyncAPI schema format.
2. Adapted the root .asyncapi property to use const instead of enum. We will never have more then one value.
3. Removed all v2 schema formats

Depending on whether this or https://github.com/asyncapi/spec-json-schemas/pull/370 is merged first, we need to adapt the function `addNewSchemaVersion`.

2023-07-07 06:19 UTC, fmvilas requested changes

2023-07-25 09:37 UTC, jonaslagoni commented
Applied your suggestions @fmvilas and applied the recent changes from master.

I adapted the add new version script so the validation of `schema` property is also changed accordingly with the right schema format values.

2023-07-25 09:37 UTC, jonaslagoni commented
Please have another look @fmvilas @derberg 🙇

2023-07-25 12:56 UTC, derberg approved these changes
LGTM 🚀 

tested on local 👇🏼 

![Screenshot 2023-07-25 at 14 55 28](https://github.com/asyncapi/spec-json-schemas/assets/6995927/7d227994-3df1-4105-b6df-26ca63c90441)
![Screenshot 2023-07-25 at 14 56 14](https://github.com/asyncapi/spec-json-schemas/assets/6995927/3e07a14a-9878-456c-9367-30af19085832)

2023-07-26 14:15 UTC, derberg commented
you mean this 👇 

![Screenshot 2023-07-26 at 16.14.52.png](https://volta.s3.fr-par.scw.cloud/Screenshot_2023_07_26_at_16_14_52_9af6af412c.png)

2023-07-26 14:16 UTC, jonaslagoni commented
/rtm

2023-07-26 14:18 UTC, derberg commented
@fmvilas is out on holidays next 4 weeks, and for not PR is blocked as he requested changes to it in the past. 

I will use admin rights to dismiss his request for changes as we won't wait a month for him

2023-07-26 14:20 UTC, merged