fix: fix type of payload and headers in MessageExample
asyncapi/spec-json-schemas pull request #561
Opened 2024-12-30 19:21 UTC by Pakisan

https://github.com/asyncapi/spec-json-schemas/issues/560

Fixes #560

2025-01-09 09:35 UTC, Pakisan commented
@derberg @fmvilas @jonaslagoni @smoya

2025-01-10 11:46 UTC, fmvilas requested changes

2025-01-10 11:46 UTC, fmvilas commented on definitions/3.0.0/messageExampleObject.json
>        "description": "Example of the application headers. It can be of any type."
Please change the description too 🙏

2025-01-10 17:11 UTC, Pakisan commented on definitions/3.0.0/messageExampleObject.json
>        "description": "Example of the application headers. It can be of any type."
Done

2025-01-10 17:17 UTC, fmvilas requested changes

2025-01-10 17:17 UTC, fmvilas commented on definitions/3.0.0/messageExampleObject.json
> +      "description": "Example of the application headers. MUST be a map of key-value pairs."
```suggestion
      "description": "Example of the application headers. It MUST be a map of key-value pairs."
```

2025-01-10 17:17 UTC, fmvilas commented on definitions/3.0.0/messageExampleObject.json
> +      "type": ["number", "string", "boolean", "object", "array", "null"],
Why maintaining a list of types here? 🤔

2025-01-10 17:36 UTC, Pakisan commented on definitions/3.0.0/messageExampleObject.json
> +      "type": ["number", "string", "boolean", "object", "array", "null"],
In previous versions here was `any` type. I found in SO that's better way to simulate any type and don't broke validation is to enumerate each JSON Schema type

2025-01-10 17:40 UTC, fmvilas commented on definitions/3.0.0/messageExampleObject.json
> +      "type": ["number", "string", "boolean", "object", "array", "null"],
Why is it going to break validation? When `type` is not specified, it can be any type, right? If some tools don't get it right, shouldn't it be fixed in the tools instead?

2025-01-10 18:15 UTC, fmvilas commented on definitions/3.0.0/messageExampleObject.json
> +      "type": ["number", "string", "boolean", "object", "array", "null"],
It's either a string or an array of strings but it's not required, so we can decide not to put it there. Effectively, I think it means "any" but good idea pinging the JSON Schema folks as, in the end, they know best.

2025-01-10 18:20 UTC, Pakisan commented on definitions/3.0.0/messageExampleObject.json
> +      "type": ["number", "string", "boolean", "object", "array", "null"],
Anyway, I'm ready to remove `type` and patch our schema for JetBrains IDE and other validators, as I have already done, previously

My main concern is to try to bring changes back, here, to make our schema compatible with various IDEs and environments where AsyncAPI specification will be validated via our JSON Schemas

And be sure that this changes are synced with JSON Schema specification requirements

2025-01-10 20:05 UTC, fmvilas commented on definitions/3.0.0/messageExampleObject.json
> +      "type": ["number", "string", "boolean", "object", "array", "null"],
Understandable mate. It's a fine line between trying to be pragmatic and keeping the spec strict. I'm not against maintaining this list of types but code you don't write is code you don't have to maintain. Arguably, explicit is better than implicit. Let's see what others have to say 🤷‍♂️ I'm not going to block this PR because of this line.

2025-01-22 15:22 UTC, derberg commented
yo, how is this one going? we need it for https://github.com/asyncapi/spec/pull/1082 to be merged

2025-01-23 12:01 UTC, fmvilas approved these changes
Approving as the discussion is non-blocking for me.

2025-01-27 09:28 UTC, merged